//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers()
        {
            this.Orders = new HashSet<Orders>();
            this.Subscriptions = new HashSet<Subscriptions>();
        }
    
        public int ID { get; set; }
        public string MicrosoftID { get; set; }
        public string CompanyName { get; set; }
        public string DomainName { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string EmailAddress { get; set; }
        public string Country { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string ZipPostal { get; set; }
        public string PhoneNumber { get; set; }
        public string State { get; set; }
        public int SpecialQualificationsID { get; set; }
        public Nullable<int> IndirectResellerID { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public string AgreementDate { get; set; }
        public bool AgreedToMCA { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual SpecialQualifications SpecialQualifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscriptions> Subscriptions { get; set; }
    }
}
