//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItems
    {
        public int ID { get; set; }
        public Nullable<int> OrdersID { get; set; }
        public Nullable<int> LineItemNumber { get; set; }
        public string OffersID { get; set; }
        public string SubscriptionID { get; set; }
        public string FriendlyName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string PartnerIdOnRecord { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Offers Offers { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
