//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscriptions
    {
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string SubscriptionID { get; set; }
        public string OffersId { get; set; }
        public string OfferName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> EffectiveStartDate { get; set; }
        public Nullable<System.DateTime> CommitmentEndDate { get; set; }
        public string Status { get; set; }
        public string BillingCycle { get; set; }
        public string OrderId { get; set; }
        public string PartnerId { get; set; }
    
        public virtual Offers Offers { get; set; }
        public virtual Customers Customers { get; set; }
    }
}
