//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccesses1
    {
        public int ID { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<bool> CanView { get; set; }
        public Nullable<bool> CanEdit { get; set; }
        public Nullable<bool> CanDelete { get; set; }
        public Nullable<bool> CanDecide { get; set; }
    
        public virtual Modules1 Modules1 { get; set; }
        public virtual UserTypes UserTypes { get; set; }
    }
}
